export const IndexScreenEntryData = {
  top: [
    {
      date: "10/18/2023",
      contact: "Tom",
      category: "Notes",
      text: "Started working on my PhD in San Francisco",
      direction: "left",
      rotation: "-5deg",
      translateXValue: -25,
      avatar: require("@/assets/images/tom.png"),
      color: "cornflowerblue",
    },
    {
      date: "11/12/2023",
      contact: "Yourself",
      category: "Event",
      text: "Just had the first date with Elsie at the coffee shop. I have a great feeling about this",
      direction: "right",
      rotation: "0deg",
      translateXValue: 150,
      avatar: require("@/assets/images/avatar.png"),
      color: "crimson",
    },
    {
      date: "10/18/2023",
      contact: "Linda",
      category: "Location",
      text: "Moved to Melbourne, Australia with Dom! Close to the woods now and a lot of nature around me",
      direction: "left",
      rotation: "5deg",
      translateXValue: -25,
      avatar: require("@/assets/images/linda.png"),
      color: "lightcoral",
    },
  ],
  bottom: [
    {
      date: "10/18/2023",
      contact: "Kim",
      category: "Personal",
      text: "29th birthday on Wednesday! Maybe get a present?",
      direction: "left",
      rotation: "-10deg",
      translateXValue: -40,
      avatar: require("@/assets/images/kim.png"),
      color: "coral",
    },
    {
      date: "10/18/2023",
      contact: "Justin",
      category: "Personal",
      text: "Graduating tomorrow",
      direction: "right",
      rotation: "5deg",
      translateXValue: 140,
      avatar: require("@/assets/images/justin.png"),
      color: "palegreen",
    },
  ],
};

export const OnboardingScreenEntryCards = [
  {
    date: "10/18/2023",
    contact: "Tom",
    category: "Notes",
    text: "Started working on my PhD in San Francisco",
    direction: "left",
    rotation: "0deg",
    avatar: require("@/assets/images/tom.png"),
    color: "cornflowerblue",
    subtext: "to keep track of important events in your friends' lives",
  },
  {
    date: "11/12/2023",
    contact: "Yourself",
    category: "Event",
    text: "Just had the first date with Elsie at the coffee shop. I have a great feeling about this",
    direction: "right",
    rotation: "0deg",
    avatar: require("@/assets/images/avatar.png"),
    color: "crimson",
    subtext:
      "where you can journal your own thoughts, your ideas and look back on what's going on",
  },
  {
    date: "10/18/2023",
    contact: "Kim",
    category: "Personal",
    text: "29th birthday on Wednesday! Maybe get a present?",
    direction: "left",
    rotation: "0deg",
    avatar: require("@/assets/images/kim.png"),
    color: "coral",
    subtext: "to never feel guilty for forgetting a friend's birthday again",
  },
  {
    date: "10/18/2023",
    contact: "Linda",
    category: "Location",
    text: "Moved to Melbourne, Australia with Dom! CLose to the woods now and a lot of nature around me",
    direction: "left",
    rotation: "0deg",
    avatar: require("@/assets/images/linda.png"),
    color: "lightcoral",
  },
  {
    date: "10/18/2023",
    contact: "Justin",
    category: "Personal",
    text: "Graduating tomorrow",
    direction: "right",
    rotation: "0deg",
    avatar: require("@/assets/images/justin.png"),
    color: "palegreen",
  },
];
